### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#11]
Where will the new web-based case management system be hosted? cloud.gov?

**Comment by randyhart** [comment]
The Court is still exploring options with respect to which FedRAMP-certified hosting solution it plans to engage. Proposals that require a particular host should so state.

**Comment by kgirkhovskiy** [comment]
Would Court provide infrastructure support for hosting, and address infrastructure security controls required for ATO or is it expected that vendor will be responsible for  such support?

**Comment by kgirkhovskiy** [comment]
Just to clarify my question.  RFP states that contractor will not be responsible for obtaining ATO, but I still believe that Contractor will need to provide an appropriate ATO support when it comes to Application level controls.

**Comment by JessicaMarine** [comment]
@kgirkhovskiy The vendor will not be required to provide any infrastructure support for hosting.  The Court will be responsible for its own ATO.  The Court will also determine which security controls are required and when they have been satisfied.  The vendor is expected to use best practices for security in delivering code.
