### ISSUE TITLE
What happens with the pending cases?

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#12]
Will the 27K pending cases need to be imported from the old system into the new? If yes, who will provide that data?

**Comment by randyhart** [comment]
The vendor will not be responsible for importing any pending case data into the new System.

**Comment by JQuaggles** [comment]
@randyhart Will the old system then be in use in tandem until only cases exist in the new system? If there was a migration effort proposed, would that be preferable so The Court is not ending up using more than one system or is it expected the migration effort would prove to be too costly/not time effective?

**Comment by JessicaMarine** [comment]
The Court does not intend to operate the old and new systems in tandem for very long, if at all.
