### ISSUE TITLE
Availability of users for research and testing

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#20]
Will the court provide the users needed for research and testing purposes?

**Comment by kwehmueller** [comment]
## Name and affiliation
Kevin Wehmueller
Taoti Creative, Business Development Strategist

## Section of RFP documents
Statement of Objectives - Description of Work to be Performed

## Question/Comment
I'd like to add a related comment from our firm to this issue. The Draft RFQ states:

> Additional Court representatives will also be promptly available as needed to assist in the development process, including for user testing.

Please specify in the final RFQ whether user testing will be limited to internal users at the Court, or whether brainstorming and implementing strategies for broader user recruitment and testing will be part of the vendor's scope of work.

**Comment by randyhart** [comment]
User testing will primarily be done by internal Court users. To the extent testing by external users is needed, the Court will arrange for that to be done.  The vendor will not be expected to assist with this.

**Comment by kaitlin** [comment]
At a glance, it looks like roughly half of the user stories in the draft SOO seem to be from external personas (Pro Se Practitioner, member of tax court bar, executor of estate, electronic filer, etc), unless I don't understand those personas. Speaking of which, it would be very helpful to see any draft personas that exist and provide any more details than the title (i.e. their motivations, pain points, etc).

**Comment by randyhart** [comment]
The System will have both internal Court users and external users.  The sample user stories provided in the RFQ are for illustrative purposes only.  The Court intends to prepare user personas as the project progresses.
