### ISSUE TITLE
Clarify "public domain" vs. "open source"

### ISSUE THREAD

**Issue by greggersh** [ustaxcourt/case-management-rfq#23]
# Question/Comment on this U.S. Tax Court RFP

## Name and affiliation
Greg Gershman, Ad Hoc LLC

## Section of RFP documents
Data Rights and Ownership of Deliverables

## Question/Comment
In regards to the software and documentation developed as part of this project, the SOO contains references both to "public domain" and "open source." There are differences between the two, we believe the government is interested in ensuring that the code developed by the vendor for this project be freely available to others, and we believe that licensing that code under an open source license (rather than contributing it to the public domain) is a better approach that will ensure the goals of the government are met. Some additional details can be found here: [https://opensource.org/node/878](https://opensource.org/node/878)

**Comment by randyhart** [comment]
Thank you for the comment.

**Comment by kwehmueller** [comment]
If the government does decide to clarify this in the final RFQ and definitively states its intention to license code under an open source license, it would be even more helpful to state whether it intends to commit the application code under an open source license _in its entirety_, or whether it intends to commit a certain percentage of the under an open source license so as to meet an applicable policy goal.

To our understanding, https://sourcecode.cio.gov/ outlines such a 20% contribution goal, however we're not entirely clear whether it still applies outside of the context of the initial pilot program. Understanding the Courts' open source contribution goal could influence vendors' overall development strategy, so we encourage as much transparency into its targets and goals as possible in the final RFQ.

**Comment by JessicaMarine** [comment]
Thank you for your comment.
