### ISSUE TITLE
Why host the dev environment somewhere else?

### ISSUE THREAD

**Issue by kaitlin** [ustaxcourt/case-management-rfq#24]
# Question/Comment on this U.S. Tax Court RFP

## Name and affiliation
Kaitlin Devine, Director of Innovation, Ad Hoc LLC

## Section of RFP documents
Appendix B, paragraph 3 - "It will be the responsibility of an EF-CMS Contractor to provide and maintain its own development environment. The Court will provide the internet-connected staging and production environments. "

## Question/Comment
What is the motivation for having a dev environment that is located in completely different infrastructure? It seems like you'd want the three environments to mirror each other as closely as possible, to minimize configuration/migration hurtles that may arise only when code is promoted to staging.

**Comment by randyhart** [comment]
The Court does not intend for the development environment to use a different infrastructure than the staging and production environments.  Rather, this statement is intended only to make clear that the Court expects the Contractor to provide and maintain its own development environment. We will encourage the Contractor to mirror the Court’s infrastructure, e.g. if staging and production are on AWS, it would be best if the Contractor hosted dev on AWS, for the reasons that you cite. If the Contractor proposes the use of an infrastructure that is more complicated (e.g., use of Court-hosted hardware), then we will reconsider this approach.
