### ISSUE TITLE
Product management/strategy capacity

### ISSUE THREAD

**Issue by kaitlin** [ustaxcourt/case-management-rfq#25]
# Question/Comment on this U.S. Tax Court RFP

## Name and affiliation
Kaitlin Devine, Director of Innovation, Ad Hoc LLC 

## Section of RFP documents
[SOO - Description of work to be performed](https://github.com/ustaxcourt/case-management-rfq/blob/master/02_SOO.md#description-of-work-to-be-performed)

## Question/Comment
There doesn't seem to be much mention of product management or product strategy in this section. Do you anticipate this as a need? Is it potentially being filled by government? If so, do you anticipate there will be a need for this in future option years?

**Comment by randyhart** [comment]
The Court intends to handle all product management and product strategy.  The Contractor will not be required to do this. However, the Contractor team should include members that are familiar with modern product management that can assist the Court in handling these roles.

**Comment by JQuaggles** [comment]
@randyhart Glad to see that The Court is being proactive and owning it from the beginning. 
Has The Court already been provided training in these areas to ensure falling back on predictive processes (and or dictation from above) does not happen? Hoping The Court has autonomy to facilitate an empirical approach which can sometimes prove challenging in the Government space.

**Comment by kaitlin** [comment]
@randyhart do you mean provide engineers and designers that are familiar with modern product management that would sometimes be asked to do PM tasks or provide a product manager that could assist on a consultative basis?

**Comment by JessicaMarine** [comment]
@kaitlin The Court does not expect the Contractor to provide engineers and designers that will be asked to do PM tasks, nor does the Court expect the Contractor to provide a product manager on a consultative basis.  Rather, the Court is simply looking for the Contractor to have team members who are familiar with product management so that they can effectively coordinate and collaborate with the Court's product manager as part of the agile process.

**Comment by JessicaMarine** [comment]
@JQuaggles The Court has been working with 18F (GSA) and other consultants regarding the preparation of the draft RFQ, as well as reviewing foundational concepts of product management.  The Court is planning to continue to work with consultants post-award, to help establish some product best practices as implementation begins.  Key Court staff will have agile training, and the individual designated as the Product Owner is a Certified Scrum Product Owner through the Scrum Alliance.  As compared to large Government entities, the Court has a fairly streamlined organizational structure that will allow the team working with the Contractor to have considerable decision-making authority.

**Comment by JQuaggles** [comment]
@JessicaMarine Thanks! That is awesome to hear.
