### ISSUE TITLE
Additional user research context

### ISSUE THREAD

**Issue by kaitlin** [ustaxcourt/case-management-rfq#26]
# Question/Comment on this U.S. Tax Court RFP

## Name and affiliation
Kaitlin Devine, Director of Innovation, Ad Hoc LLC 

## Section of RFP documents
[SOO - Description of work to be performed](https://github.com/ustaxcourt/case-management-rfq/blob/master/02_SOO.md#description-of-work-to-be-performed) - “The Court expects the development process will consist of 2-week sprint cycles, and that the initial phases of the development process will focus on providing identity and access management, case initiation, payment of fees, search functionality, e-signatures, notes, and content management.”

## Question/Comment
Are there any existing user research artifacts that could provide more context on why these particular items were prioritized into the initial phases? For example, these are features but is there more background on the value and outcomes you want these features to achieve?

**Comment by randyhart** [comment]
The sample user stories contained in the RFQ are for illustrative purposes only.  The full scope of the project is outlined in Appendix C. The Court expects to work with the vendor to develop and prioritize a full gamut of user stories as the project progresses.
