### ISSUE TITLE
Clarify parameters of existing system

### ISSUE THREAD

**Issue by kaitlin** [ustaxcourt/case-management-rfq#27]
# Question/Comment on this U.S. Tax Court RFP

## Name and affiliation
Kaitlin Devine, Director of Innovation, Ad Hoc LLC

## Section of RFP documents
[SOO - Introduction](https://github.com/ustaxcourt/case-management-rfq/blob/master/02_SOO.md#introduction) - "The Court currently uses a legacy case management system that is not web-based. The Court holds a license to use the software that supports that system. Under the terms of that license, the Court is precluded from disclosing any programs, concepts, designs, or source code. This may be an important operating constraint for the Contractor because it will not be able to view or access the current system in any way."

## Question/Comment
Does "not web-based" mean this is a desktop client installed on individual workstations that share a common, networked database?

**Comment by randyhart** [comment]
Yes. However, we want the future System to be web-based.
