### ISSUE TITLE
Provide more context for the self-hosted/cloud-hosted hybrid model described in Appendix B

### ISSUE THREAD

**Issue by kaitlin** [ustaxcourt/case-management-rfq#28]
# Question/Comment on this U.S. Tax Court RFP

## Name and affiliation
Kaitlin Devine, Director of Innovation, Ad Hoc LLC 

## Section of RFP documents
Appendix B - "The Court expects that the hardware and software comprising the EF-CMS will either be located on premise, or on a FedRAMP-certified cloud storage solution controlled by the Court, or some hybrid thereof."

## Question/Comment
Could you talk more about the specific Court needs being met by the self-hosted infrastructure that cannot be met with cloud infrastructure? It would be really helpful to understand the specific needs and the trade-offs the Court is considering in this decision. A hybrid environment would certainly add to the complexity, as well as the portfolio of skillsets needed to manage both environments. But there may be some data or functionality that can't be moved out of the environment that makes the added complexity worth it. Either way, it would be really helpful to explain that here. 

Especially since elsewhere in this section, the draft states: "Offerors must state in their quote whether additional hardware, software or ancillary equipment is required for the development, staging, or production environments, and provide details including associated estimated costs."

It's pretty hard to be able to address that section without knowing what the Court specifically wants to use the self-hosted environment for. Is it database management? Some kind of internal user authentication?

**Comment by randyhart** [comment]
Thank you for your comment.  The Court is willing to consider all proposals, and has flexibility when it comes to the hosting of environments.   We believe that this will allow vendors to propose an innovative solution that addresses both the Court’s functional and security needs.
