### ISSUE TITLE
e-mailed question regarding licensing models

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#29]
**_Note that the Tax Court indicated to vendors we wouldn't attribute their emailed comments when posting on GitHub so that we could cast as wide a net as possible. That's why portions of the following issue are redacted._**

 This email is in response to the Draft RFQ for the U.S. Tax Courts Enterprise.  **[Redacted]** only has a few questions and comments.  

1) We recommend that the term "free open source software" be changed to "open source software".  **[Redacted]**'s open source case management software platform is a paid annual subscription that includes the software license based on Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html), support and maintenance.  We would not be able to offer the software free of charge.  However, our annual subscription model does provide low cost of entry, predictability and can significantly decrease the amount of time it takes to implement and maintain an application which also reduces labor costs.<br><br>While "free" open source software exists, they sometimes come in various forms.  A vendor may offer a Community Edition and an Enterprise Edition.  A Community version could be free, but would be very limited.  For example, community versions do not allow for high availability, they do not offer a dedicated support team and new versions do not go through rigorous Quality Assurance testing.  Enterprise Editions, however, are not considered "free" open source.  Instead they are considered Open Core and have similar license model as **[Redacted]**. 

2) Would enterprise (not free) open source software be considered material under the T&M contract?  If not, we would recommend a procurement that allows for the purchase of software and labor.

**Comment by JessicaMarine** [comment]
1.Thank you for your recommendation and comment.  The Court will consider it carefully as we go forward.

2.The posted version of the draft RFQ does not contemplate a submission that includes charges for software licenses.

**Comment by jab121** [comment]
I think this is a great ideal, "free open source"  The government should do more procurements like this so that funds can go further.

**Comment by JessicaMarine** [comment]
@jab121 Thank you for the comment.
