### ISSUE TITLE
Payment Gateway

### ISSUE THREAD

**Issue by AjieVelasquez** [ustaxcourt/case-management-rfq#30]
# Question/Comment on this U.S. Tax Court RFP
On page 7, User Stories, Fees, What is the payment gateway that will be used?

## Name and affiliation
Ajie Velasquez, Vice President, Armedia, LLC 

## Section of RFP documents
Page 7, User Stories, Fees, 

## Question/Comment
What is the payment gateway that will be used?

**Comment by JessicaMarine** [comment]
The Court currently uses pay.gov
