### ISSUE TITLE
E-mailed question about Evaluation Criteria

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#31]
Evaluation criteria states that we need to submit "links to Git repositories​". If these repos are not public, is there a github user that we can add? Is this the only way that the Court will evaluate the relevance of a vendor's technical and subject matter expertise?

**Comment by JessicaMarine** [comment]
If an offeror submits a link to a private Git repository hosted with GitHub, the Court will provide the offeror with one or more GitHub user identities by email, and the offeror will be expected to promptly provide the identified user(s) with access to the Git repository.  The Court expects that the extent of an offeror’s technical and subject matter expertise will be revealed through the offeror’s technical proposal, staffing plan, and Git repositories.
