### ISSUE TITLE
e-mailed question about "Work to be Performed" (Page 3)

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#32]
The RFI states "The Contractor must provide services that will include all aspects of the software development process, including initial planning, design...and deployment into the Court’s pre-production environment."

 Does "the Court's pre-production environment" refer to an environment that the Court has already set up, similar to its current production environment? Or will "the Court's pre-production environment" be one that the Contractor sets up / creates?

**Comment by JessicaMarine** [comment]
Thank you for your comment.  The Court is considering making changes to the final RFQ based on your feedback.  The Court no longer intends for the Contractor to be responsible for deployment of the developed code into the Court’s pre-production environment.  Rather, the Court will be responsible for deployment of the developed code into the Court’s pre-production environment.  The Court will provide and maintain the Court’s pre-production environment.
