### ISSUE TITLE
e-mailed question about processing of filings (appendix C)

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#33]
A Tax Court case can be initiated via a paper filing. The RFI states that "many Petitions do not conform with the Tax Court Rules, and some of the documents submitted will not become part of the official docket record. The Court expects a future EF-CMS will allow for the processing of these documents that are not part of the record." How is this information stored currently, and is there any migration of this data that needs to happen?

What kind of processing is needed on these documents?

**Comment by JessicaMarine** [comment]
The docket record contains a chronological list of all pleadings and other documents filed in a case.  Documents that are submitted and do not become part of the official docket record should be associated with the case and viewable by internal Court users only.  The Contractor will not be required to provide services relating to data migration.
