### ISSUE TITLE
e-mailed question about scanning and verifying checks for payment (Appendix C)

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#34]
"In addition, the System will allow for payment of filing fees by check. If paid by check, a Court employee will scan thecheck for automatic transmittal to the U.S. Treasury. Checks that cannot be scanned for automatic transmission will be manually delivered to the U.S. Treasury."

Does the EF-CMS system need to scan and verify checks? Or is that done separately and all the EF-CMS system needs to do is manage of payments workflow and documentation?
--

**Comment by JessicaMarine** [comment]
The System will not need to either scan or verify checks.  However, the System will need to manage the workflow and documentation of the payments.
