### ISSUE TITLE
e-mailed question about payment of filing fees (Appendix C)

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#35]
"In addition, the System will allow for payment of filing fees by check. If paid by check, a Court employee will scan the check for automatic transmittal to the U.S. Treasury. Checks that cannot be scanned for automatic transmission will be manually delivered to the U.S. Treasury."

Is this done manually right now? Is the EF-CMS system expected to do this automatically?

**Comment by JessicaMarine** [comment]
The System will not need to either scan or verify checks.  However, the System will need to manage the workflow and documentation of the payments.
