### ISSUE TITLE
e-mailed question about whether the system should be searchable (appendix C)

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#36]
"A future EF-CMS will allow for calendaring sealed hearings or portions thereof for which Court staff need access to the scheduling information but the public does not, and for permitting an internal search for the name of a petitioner where the public-facing name is “Anonymous”."

Does this mean that most court filings for this system should be easily searchable by the public? What kind of data in the system needs to be made publicly available?

**Comment by JessicaMarine** [comment]
All filings should be easily searchable.  Adjustable permissions will control which filings can be viewed and searched by internal Court users and the public.  Generally, only docket sheets, Orders, Opinions are viewable by the public.
