### ISSUE TITLE
e-mailed question about how the Court will evaluate technical and subject matter expertise (Basis of Award and Evaluation Factors) 

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#37]
How will the Tax Court evaluate similar experience beyond the github links that each vendor provides? Where in the response should the vendor describe their technical experience and subject matter expertise?

**Comment by JessicaMarine** [comment]
The Court intends to evaluate similar experience through any available means, including public websites. The Court expects that the extent of an offeror’s technical and subject matter expertise will be revealed through the offeror’s technical proposal, staffing plan, and Git repositories.
