### ISSUE TITLE
e-mailed question about the Court's expected MVP functionality

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#39]
Will the Court want to begin this work with an MVP?  If so, what basic functionality comprises an EF-CMS MVP?

**Comment by JessicaMarine** [comment]
The Court currently contemplates a MVP that will include the ability to electronically file documents (including case initiation documents), and the ability for the Court to route those filings to the appropriate internal Court users, take action on those filings, and serve filings and orders on the parties.
