### ISSUE TITLE
e-mailed question about the Court's approach to product management and strategy

### ISSUE THREAD

**Issue by randyhart** [ustaxcourt/case-management-rfq#40]
It appears that the Court will handle product management and product strategy.  Could the Court outline their approach/goals for product?

**Comment by JessicaMarine** [comment]
The Court has already assigned a Product Owner to lead the team.  The Product Owner will set direction, make prioritization choices/build a product roadmap, ensure the product solves the right problems for the right people throughout development, and support everyone else on the team.  Offerors are welcome to describe their proposed approach to supporting product management in their technical proposal or their staffing plan.  The goal is to provide a fully functional case management system.  The scope of the project is outlined in Appendix C.
